// Mock data for testing without Supabase

export const mockProducts = [
  {
    id: "1",
    name: "국내산 돼지고기 (삼겹살)",
    category: "육류",
    unit: "kg",
    price: 15000,
    description: "신선한 국내산 돼지 삼겹살",
    image_path: "https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=400",
    stock: 100,
    min_order: 5,
    seller_id: "seller1",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "유기농 감자",
    category: "채소",
    unit: "kg",
    price: 3500,
    description: "무농약 유기농 감자",
    image_path: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    stock: 200,
    min_order: 10,
    seller_id: "seller1",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "양파 (국내산)",
    category: "채소",
    unit: "kg",
    price: 2500,
    description: "국내산 신선 양파",
    image_path: "https://images.unsplash.com/photo-1587049352846-4a222e784720?w=400",
    stock: 150,
    min_order: 10,
    seller_id: "seller2",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "당근 (유기농)",
    category: "채소",
    unit: "kg",
    price: 4000,
    description: "유기농 인증 당근",
    image_path: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
    stock: 120,
    min_order: 10,
    seller_id: "seller2",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "한우 (국거리용)",
    category: "육류",
    unit: "kg",
    price: 45000,
    description: "1등급 한우 국거리용",
    image_path: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    stock: 50,
    min_order: 3,
    seller_id: "seller1",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "대파",
    category: "채소",
    unit: "kg",
    price: 3000,
    description: "국내산 대파",
    image_path: "https://images.unsplash.com/photo-1629798956579-e658c8ca6e89?w=400",
    stock: 80,
    min_order: 5,
    seller_id: "seller2",
    created_at: new Date().toISOString(),
  },
];

export const mockRecipes = [
  {
    id: "1",
    name: "김치찌개",
    description: "김치찌개 레시피 (100인분)",
    category: "한식당",
    servings: 100,
    ingredients: [
      { product_id: "1", quantity: 3, unit: "kg", product_name: "국내산 돼지고기 (삼겹살)" },
      { product_id: "2", quantity: 2, unit: "kg", product_name: "유기농 감자" },
      { product_id: "3", quantity: 1, unit: "kg", product_name: "양파 (국내산)" },
      { product_id: "6", quantity: 0.5, unit: "kg", product_name: "대파" },
    ],
    instructions: "1. 돼지고기를 볶는다\n2. 김치를 넣고 볶는다\n3. 물을 붓고 끓인다\n4. 감자, 양파를 넣는다\n5. 대파를 넣고 마무리",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "카레라이스",
    description: "카레 레시피 (100인분)",
    category: "양식당",
    servings: 100,
    ingredients: [
      { product_id: "5", quantity: 5, unit: "kg", product_name: "한우 (국거리용)" },
      { product_id: "2", quantity: 4, unit: "kg", product_name: "유기농 감자" },
      { product_id: "4", quantity: 2, unit: "kg", product_name: "당근 (유기농)" },
      { product_id: "3", quantity: 2, unit: "kg", product_name: "양파 (국내산)" },
    ],
    instructions: "1. 고기와 야채를 썬다\n2. 고기를 볶는다\n3. 야채를 넣고 볶는다\n4. 물을 붓고 끓인다\n5. 카레 루를 넣고 완성",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "짜장면",
    description: "짜장면 레시피 (50인분)",
    category: "중식당",
    servings: 50,
    ingredients: [
      { product_id: "1", quantity: 2, unit: "kg", product_name: "국내산 돼지고기 (삼겹살)" },
      { product_id: "3", quantity: 3, unit: "kg", product_name: "양파 (국내산)" },
      { product_id: "2", quantity: 1, unit: "kg", product_name: "유기농 감자" },
    ],
    instructions: "1. 춘장을 볶는다\n2. 고기를 넣고 볶는다\n3. 야채를 넣고 볶는다\n4. 물을 붓고 끓인다\n5. 전분물로 농도 조절",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "돈까스",
    description: "돈까스 레시피 (50인분)",
    category: "일식당",
    servings: 50,
    ingredients: [
      { product_id: "1", quantity: 5, unit: "kg", product_name: "국내산 돼지고기 (삼겹살)" },
      { product_id: "2", quantity: 2, unit: "kg", product_name: "유기농 감자" },
    ],
    instructions: "1. 돼지고기를 두드린다\n2. 밀가루-계란-빵가루 순으로 묻힌다\n3. 180도 기름에 튀긴다\n4. 소스와 함께 제공",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "떡볶이",
    description: "떡볶이 레시피 (100인분)",
    category: "분식점",
    servings: 100,
    ingredients: [
      { product_id: "3", quantity: 2, unit: "kg", product_name: "양파 (국내산)" },
      { product_id: "6", quantity: 1, unit: "kg", product_name: "대파" },
    ],
    instructions: "1. 육수를 낸다\n2. 떡과 어묵을 넣는다\n3. 고춧가루로 간한다\n4. 양파, 대파를 넣고 끓인다",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "샌드위치",
    description: "샌드위치 레시피 (50인분)",
    category: "카페",
    servings: 50,
    ingredients: [
      { product_id: "4", quantity: 1, unit: "kg", product_name: "당근 (유기농)" },
      { product_id: "3", quantity: 0.5, unit: "kg", product_name: "양파 (국내산)" },
    ],
    instructions: "1. 야채를 씻어 준비한다\n2. 빵에 버터를 바른다\n3. 야채와 치즈를 올린다\n4. 빵을 덮고 자른다",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
];

export const mockOrders = [
  {
    id: "1",
    user_id: "user1",
    status: "pending" as const,
    total_amount: 150000,
    delivery_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "1-1",
        order_id: "1",
        product_id: "1",
        quantity: 10,
        price_at_order: 15000,
        product: {
          name: mockProducts[0].name,
          unit: mockProducts[0].unit,
          image_path: mockProducts[0].image_path,
        },
      },
    ],
  },
  {
    id: "2",
    user_id: "user1",
    status: "preparing" as const,
    total_amount: 180000,
    delivery_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "2-1",
        order_id: "2",
        product_id: "5",
        quantity: 4,
        price_at_order: 45000,
        product: {
          name: mockProducts[4].name,
          unit: mockProducts[4].unit,
          image_path: mockProducts[4].image_path,
        },
      },
    ],
  },
];

export const mockUser = {
  id: "user1",
  email: "test@smeats.com",
  name: "테스트 사용자",
  role: "customer" as const,
  organization: "테스트 식당",
  created_at: new Date().toISOString(),
};

// Persona-based demo users
export type PersonaType = "buyer" | "seller" | "admin";

export const mockUsers = {
  buyer: {
    id: "buyer-demo-1",
    email: "demo-buyer@smeats.com",
    name: "김사장",
    role: "customer" as const,
    organization: "맛있는 한식당",
    phone: "010-1234-5678",
    address: "서울시 강남구 테헤란로 123",
    region: "서울시 강남구",
    business_type: "한식당",
    store_name: "맛있는 한식당",
    created_at: new Date().toISOString(),
  },
  seller: {
    id: "seller-demo-1",
    email: "demo-seller@smeats.com",
    name: "이판매",
    role: "seller" as const,
    business_name: "신선마트",
    business_registration: "123-45-67890",
    contact_phone: "010-9876-5432",
    address: "서울시 송파구 송파대로 456",
    created_at: new Date().toISOString(),
  },
  admin: {
    id: "admin-demo-1",
    email: "demo-admin@smeats.com",
    name: "관리자",
    role: "admin" as const,
    created_at: new Date().toISOString(),
  },
};

// Buyer's orders (주문 내역)
export const mockBuyerOrders = [
  {
    id: "buyer-order-1",
    user_id: "buyer-demo-1",
    seller_id: "seller-demo-1",
    seller_name: "신선마트",
    status: "pending" as const,
    total_amount: 150000,
    delivery_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "buyer-order-1-1",
        order_id: "buyer-order-1",
        product_id: "1",
        quantity: 10,
        price_at_order: 15000,
        product: {
          name: mockProducts[0].name,
          unit: mockProducts[0].unit,
          image_path: mockProducts[0].image_path,
        },
      },
    ],
  },
  {
    id: "buyer-order-2",
    user_id: "buyer-demo-1",
    seller_id: "seller-demo-1",
    seller_name: "신선마트",
    status: "preparing" as const,
    total_amount: 180000,
    delivery_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "buyer-order-2-1",
        order_id: "buyer-order-2",
        product_id: "5",
        quantity: 4,
        price_at_order: 45000,
        product: {
          name: mockProducts[4].name,
          unit: mockProducts[4].unit,
          image_path: mockProducts[4].image_path,
        },
      },
    ],
  },
  {
    id: "buyer-order-3",
    user_id: "buyer-demo-1",
    seller_id: "seller-demo-1",
    seller_name: "신선마트",
    status: "delivered" as const,
    total_amount: 95000,
    delivery_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "buyer-order-3-1",
        order_id: "buyer-order-3",
        product_id: "2",
        quantity: 10,
        price_at_order: 3500,
        product: {
          name: mockProducts[1].name,
          unit: mockProducts[1].unit,
          image_path: mockProducts[1].image_path,
        },
      },
      {
        id: "buyer-order-3-2",
        order_id: "buyer-order-3",
        product_id: "6",
        quantity: 20,
        price_at_order: 3000,
        product: {
          name: mockProducts[5].name,
          unit: mockProducts[5].unit,
          image_path: mockProducts[5].image_path,
        },
      },
    ],
  },
];

// Seller's received orders (받은 주문)
export const mockSellerOrders = [
  {
    id: "seller-order-1",
    user_id: "buyer-demo-1",
    seller_id: "seller-demo-1",
    buyer_name: "김사장",
    buyer_organization: "서울특별시 성북구",
    status: "pending" as const,
    total_amount: 150000,
    delivery_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울특별시 성북구 동소문로 789",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "seller-order-1-1",
        order_id: "seller-order-1",
        product_id: "1",
        quantity: 10,
        price_at_order: 15000,
        product: {
          name: mockProducts[0].name,
          unit: mockProducts[0].unit,
          image_path: mockProducts[0].image_path,
        },
      },
    ],
  },
  {
    id: "seller-order-2",
    user_id: "buyer-demo-2",
    seller_id: "seller-demo-1",
    buyer_name: "박사장",
    buyer_organization: "서울특별시 성북구",
    status: "preparing" as const,
    total_amount: 225000,
    delivery_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울특별시 성북구 정릉로 123",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "seller-order-2-1",
        order_id: "seller-order-2",
        product_id: "5",
        quantity: 5,
        price_at_order: 45000,
        product: {
          name: mockProducts[4].name,
          unit: mockProducts[4].unit,
          image_path: mockProducts[4].image_path,
        },
      },
    ],
  },
  {
    id: "seller-order-3",
    user_id: "buyer-demo-3",
    seller_id: "seller-demo-1",
    buyer_name: "최사장",
    buyer_organization: "서울특별시 성북구",
    status: "shipped" as const,
    total_amount: 95000,
    delivery_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울특별시 성북구 보문로 456",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "seller-order-3-1",
        order_id: "seller-order-3",
        product_id: "2",
        quantity: 10,
        price_at_order: 3500,
        product: {
          name: mockProducts[1].name,
          unit: mockProducts[1].unit,
          image_path: mockProducts[1].image_path,
        },
      },
      {
        id: "seller-order-3-2",
        order_id: "seller-order-3",
        product_id: "6",
        quantity: 20,
        price_at_order: 3000,
        product: {
          name: mockProducts[5].name,
          unit: mockProducts[5].unit,
          image_path: mockProducts[5].image_path,
        },
      },
    ],
  },
];

// Admin statistics
export const mockAdminStats = {
  totalUsers: 145,
  totalBuyers: 89,
  totalSellers: 52,
  totalAdmins: 4,
  totalOrders: 1234,
  totalRevenue: 45600000,
  monthlyRevenue: 8900000,
  pendingOrders: 23,
  preparingOrders: 45,
  shippedOrders: 67,
  deliveredOrders: 1099,
  activeProducts: 234,
  pendingProducts: 12,
};

// Seller statistics
export const mockSellerStats = {
  totalOrders: 89,
  monthlyOrders: 23,
  totalRevenue: 12300000,
  monthlyRevenue: 3200000,
  pendingOrders: 1,
  preparingOrders: 1,
  shippedOrders: 1,
  activeProducts: 6,
};
