// Mock data for testing without Supabase

export const mockProducts = [
  {
    id: "1",
    name: "국내산 돼지고기 (삼겹살)",
    category: "육류",
    unit: "kg",
    price: 15000,
    description: "신선한 국내산 돼지 삼겹살",
    image_url: "https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=400",
    stock: 100,
    min_order: 5,
    seller_id: "seller1",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "유기농 감자",
    category: "채소",
    unit: "kg",
    price: 3500,
    description: "무농약 유기농 감자",
    image_url: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    stock: 200,
    min_order: 10,
    seller_id: "seller1",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "양파 (국내산)",
    category: "채소",
    unit: "kg",
    price: 2500,
    description: "국내산 신선 양파",
    image_url: "https://images.unsplash.com/photo-1587049352846-4a222e784720?w=400",
    stock: 150,
    min_order: 10,
    seller_id: "seller2",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "당근 (유기농)",
    category: "채소",
    unit: "kg",
    price: 4000,
    description: "유기농 인증 당근",
    image_url: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
    stock: 120,
    min_order: 10,
    seller_id: "seller2",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "한우 (국거리용)",
    category: "육류",
    unit: "kg",
    price: 45000,
    description: "1등급 한우 국거리용",
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    stock: 50,
    min_order: 3,
    seller_id: "seller1",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "대파",
    category: "채소",
    unit: "kg",
    price: 3000,
    description: "국내산 대파",
    image_url: "https://images.unsplash.com/photo-1629798956579-e658c8ca6e89?w=400",
    stock: 80,
    min_order: 5,
    seller_id: "seller2",
    created_at: new Date().toISOString(),
  },
];

export const mockRecipes = [
  {
    id: "1",
    name: "김치찌개",
    description: "급식용 김치찌개 레시피 (100인분)",
    servings: 100,
    ingredients: [
      { product_id: "1", quantity: 3, unit: "kg", product_name: "국내산 돼지고기 (삼겹살)" },
      { product_id: "2", quantity: 2, unit: "kg", product_name: "유기농 감자" },
      { product_id: "3", quantity: 1, unit: "kg", product_name: "양파 (국내산)" },
      { product_id: "6", quantity: 0.5, unit: "kg", product_name: "대파" },
    ],
    instructions: "1. 돼지고기를 볶는다\n2. 김치를 넣고 볶는다\n3. 물을 붓고 끓인다\n4. 감자, 양파를 넣는다\n5. 대파를 넣고 마무리",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "카레라이스",
    description: "급식용 카레 레시피 (100인분)",
    servings: 100,
    ingredients: [
      { product_id: "5", quantity: 5, unit: "kg", product_name: "한우 (국거리용)" },
      { product_id: "2", quantity: 4, unit: "kg", product_name: "유기농 감자" },
      { product_id: "4", quantity: 2, unit: "kg", product_name: "당근 (유기농)" },
      { product_id: "3", quantity: 2, unit: "kg", product_name: "양파 (국내산)" },
    ],
    instructions: "1. 고기와 야채를 썬다\n2. 고기를 볶는다\n3. 야채를 넣고 볶는다\n4. 물을 붓고 끓인다\n5. 카레 루를 넣고 완성",
    created_by: "user1",
    created_at: new Date().toISOString(),
  },
];

export const mockOrders = [
  {
    id: "1",
    user_id: "user1",
    status: "pending" as const,
    total_amount: 150000,
    delivery_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "1-1",
        order_id: "1",
        product_id: "1",
        quantity: 10,
        price_at_order: 15000,
        product: {
          name: mockProducts[0].name,
          unit: mockProducts[0].unit,
          image_path: mockProducts[0].image_url,
        },
      },
    ],
  },
  {
    id: "2",
    user_id: "user1",
    status: "preparing" as const,
    total_amount: 180000,
    delivery_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    delivery_address: "서울시 강남구 테헤란로 123",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "2-1",
        order_id: "2",
        product_id: "5",
        quantity: 4,
        price_at_order: 45000,
        product: {
          name: mockProducts[4].name,
          unit: mockProducts[4].unit,
          image_path: mockProducts[4].image_url,
        },
      },
    ],
  },
];

export const mockUser = {
  id: "user1",
  email: "test@smeats.com",
  name: "테스트 사용자",
  role: "customer" as const,
  organization: "테스트 학교",
  created_at: new Date().toISOString(),
};
